### ISSUE TITLE
Query dataset with no depth

### ISSUE THREAD

**Issue by loicbachelot** [CMCC-Foundation/bluecloud-mockup_method#4]
[CHL_query.txt](https://github.com/CMCC-Foundation/bluecloud-mockup_method/files/6574060/CHL_query.txt)

To query the dataset OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041, we shouldn't specify a depth and the final request should be like the one attached. But this option isn't available in the download module.

**Comment by anto6715** [comment]
Hi @loicbachelot, with the last commit I added the support to the datasets without depth.
I also added a dataset in the config files and you can already download it.

In datasets without depth, it is important not to include this parameter in the configuration file.
If the code works ok, you can close the issue, otherwise let me know if there are some problems

**Comment by loicbachelot** [comment]
Hi @anto6715 
Everything works perfectly for me, thanks!
